version: '3.4'
services:
  answer-machine:
    build:
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    volumes:
      - ~/ws/olihock/answer-machine-instance-volume:/app/instance
    networks:
      - answer-machine
      - weaviate_weaviate-network
      - documentdb_documentdb-network
networks:
  answer-machine:
  weaviate_weaviate-network:
    external: true
  documentdb_documentdb-network:
    external: true
