version: '3.4'
services:
  answer-machine:
    build:
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    networks:
      - weaviate_weaviate-network
      - documentdb_documentdb-network
      - keycloak_keycloak-network
networks:
  weaviate_weaviate-network:
    external: true
  documentdb_documentdb-network:
    external: true
  keycloak_keycloak-network:
    external: true