version: '3.4'
services:
  answer-machine:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "10000:5000"
    networks:
      - answer-machine
      - weaviate_weaviate-network
      - documentdb_documentdb-network
networks:
  answer-machine:
  weaviate_weaviate-network:
    external: true
  documentdb_documentdb-network:
    external: true
