version: '3.4'
services:
  answer-machine:
    build:
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    networks:
      - weaviate_weaviate-network
networks:
  weaviate_weaviate-network:
    external: true