version: '3.4'
services:
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
      # NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA
    networks:
      - weaviate-network
  weaviate:
    image: semitechnologies/weaviate:1.21.2
    ports:
      - "10002:8080"
    env_file:
      - weaviate.env
    volumes:
      - weaviate-data:/weaviate-data
    depends_on:
      - t2v-transformers
    networks:
      - weaviate-network
volumes:
  weaviate-data:
networks:
  weaviate-network:
