version: '3.4'
services:
  documentdb:
    image: postgres:15.4
    ports:
      - "5433:5432"
    env_file:
      - documentdb.env
    volumes:
      - ~/ws/olihock/documentdb-volume:/var/lib/postgresql/data
    networks:
      - documentdb-network
networks:
  documentdb-network:
